name: Deploy to network with version

on:
  workflow_dispatch:
    inputs:
      network:
        type: choice
        description: Select network
        options:
        - rinkeby
        - goerli
        - mainnet
        - polygon
      version:
        required: true
jobs:
  deploy:
    if: github.repository_owner == github.actor
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Setup yarn
        run: npm install -g yarn
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Codegen and build
        run: yarn prepare:${{ github.event.inputs.network }} && yarn codegen && yarn build
      - name: Run tests
        run: yarn run test
      - name: Auth
        run: yarn graph auth --product hosted-service ${{ secrets.GRAPH_ACCESS_TOKEN }}
      - name: Deploy
        run: yarn run deploy:${{ github.event.inputs.network }} -l "${{ github.event.inputs.version }}"
